#!/bin/bash
#
# This program sends an email summarizing the usage of 
# the Aether lab storage servers.
#
# This can be run as a stand-alone program, but the intended
# use is to be run automatically at some fixed
# period (like a week) as a cron job.
# 
# To get this to work, modify the crontab file using:
# $ crontab -e
#
# To send a weekly email summarizing the 
# disk usage on the servers, add the 
# following line to the crontab file:
#
# 00 00 * * 0 /home/shannon/a/aether/.bin/server-usage-summary/mail_aether_disk_usage
#
# See the crontab documentation 
# for details about what the digits and asterisks mean,
# but briefly they specifiy when to run the job.
# The above line runs this email script every Sunday at 12:00 AM. 
#
# Written by
# Matthew Giarra
# December 25, 2016
# (Merry Christmas)
# matthew.giarra@gmail.com
#
# This line creates the subject line for the email.
SUBJECT="$(echo "Aether Lab server usage summary for $(date +"%m-%d-%Y")")"

# Specify the email recipient.
# Once I get permissions to send emails
# to the Aether list serve,
# change this line to EMAIL_RECIPIENT=aether-list
# or whatever is the correct recipient to message the group.
# Currently the list aether_list is specified in the
# file /home/shannon/a/aether/.mailrc
EMAIL_RECIPIENT=aether_list

# Now call the usage measurement program and email it to the listserv.
/home/shannon/a/aether/.bin/server-usage-summary/measure_aether_disk_usage | mailx -s "$SUBJECT" -c mgiarra,bhattac3,bjun,chakrab3,guo246,mbrindis,meyers18,pvlachos,saramide,xu427,zhan1589

